site_name: My Documentation
theme:
  name: material
  language: zh  # 默认语言，可切换为多语言

# https://www.mkdocs.org/user-guide/writing-your-docs/
nav:
  - Home: index.md

# 开启搜索功能
extra:
  search:
    language: 'zh'

# https://ultrabug.github.io/mkdocs-static-i18n/setup/choosing-the-structure/
plugins:
  - search
  - i18n:
      docs_structure: suffix
      default_language: zh
      languages:
        - locale: zh
          name: 简体中文
          build: true
          default: true
          site_name: "MediaPipe4U 文档"
        - locale: en
          name: English
          build: false
          site_name: "MediaPipe4U Documents"

#https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences