site_name: MediaPipe4U Documentation
site_url: https://opensource.labijie.com/Mediapipe4u-plugin
edit_uri: blob/main/docs/
repo_url: https://github.com/endink/Mediapipe4u-plugin

docs_dir: docs/

theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path #https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections-with-sections
    - toc.integrate
    - navigation.top

# https://www.mkdocs.org/user-guide/writing-your-docs/
nav:
  - Home: index.md
  - Setup: 
    - install/requirement.md
    - install/install.md
    - install/gstreamer.md
  - FAQ: 
    - faq/index.md

exclude_docs: |
  _config.yml   
  debug.yml
  gemfile
  Dockerfile

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ultrabug/mkdocs-static-i18n
      name: mkdocs-static-i18n on Github

# https://ultrabug.github.io/mkdocs-static-i18n/setup/choosing-the-structure/
plugins:
  - search
  - i18n: 
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
      fallback_to_default: true
      languages:
        - locale: zh
          name: 简体中文
          build: true
          default: true
          site_name: "MediaPipe4U 文档"
          nav_translations: 
            Home: 首页
            Setup: 安装
            FAQ: 常见问题
        - locale: en
          name: English
          build: true
          site_name: "MediaPipe4U Documents"

#https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight: 
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji: 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true