site_name: MediaPipe4U Documentation
theme:
  name: material
  language: zh

# https://www.mkdocs.org/user-guide/writing-your-docs/
nav:
  - Home: index.md

extra:
  search:
    language: 'zh'

# https://ultrabug.github.io/mkdocs-static-i18n/setup/choosing-the-structure/
plugins:
  - search
  - i18n:
      docs_structure: folder
      default_language: zh
      reconfigure_material: true
      fallback_to_default: true
      languages:
        - locale: zh
          name: 简体中文
          build: true
          default: true
          site_name: "MediaPipe4U 文档"
        - locale: en
          name: English
          build: true
          site_name: "MediaPipe4U Documents"

#https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true