name: 🐛 Bug Report (English)
description: File a bug report
assignees:
  - endink
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: m4uver
    attributes:
      label: MediaPipe4U Version
      placeholder: Which version of MediaPipe4U you used, for example, 20230311.
    validations:
      required: true
  - type: dropdown
    id: ueversion
    attributes:
      label: UE Version
      description: Which version of Unreal Engine you used.
      options:
        - 5.0.x
        - 5.1.x
        - 5.2.x
        - 5.3.x
    validations:
      required: true
  - type: dropdown
    id: uetype
    attributes:
      label: UnrealEngine Type
      description: Which type of Unreal Engine you used, very important for some issues.
      options:
        - Install From Epic Games Launcher 
        - Compiled From Source Code
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform your application used.
      options:
        - Windows
        - Android
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: If possible, drag and drop files into the input box to upload upload log files, screenshots, etc. to help me quickly locate the issue.
      placeholder: Tell us what you see!
    validations:
      required: true