name: Bug Report
description: File a bug report
title: "[Bug]: "
assignees:
  - endink
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: m4uver
    attributes:
      label: MediaPipe4U Version
      placeholder: Which version of MediaPipe4U you used.
    validations:
      required: true
  - type: dropdown
    id: ueversion
    attributes:
      label: UE Version
      description: Which version of Unreal Engine you used.
      options:
        - 5.0.x
        - 5.1.x
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true