# title: MediaPipe4U Doc
# lang: zh-cn
# description: 基于 MediaPipe 的 UnrealEngine 动补插件

# # remote_theme: rundocs/jekyll-rtd-theme\
# remote_theme: mmistakes/minimal-mistakes

# readme_index:
#   with_frontmatter: true

# exclude:
#   - Makefile
#   - CNAME
#   - Gemfile
#   - Gemfile.lock

title: MediaPipe4U Doc
lang: zh-cn
description: 基于 MediaPipe 的 UnrealEngine 动补插件

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

