title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://github.coms/endink/mediapipe4u-plugin


theme: just-the-docs


exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-default-layout

