title: MediaPipe4U
description: UnrealEngine 插件，基于 Google MediaPipe 完成单目单目摄像头动作捕捉、表情捕捉

url: https://opensource.labijie.com
repository: endink/mediaipe4u-plugin # for github-metadata
remote_theme: just-the-docs/just-the-docs@v0.10.1
# color_scheme: dark

lang: "zh"
# _config.yml
languages:
  - en
  - zh


exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-default-layout
  - jemoji
  - jekyll-multiple-languages-plugin

nav_external_links:
  - title: Demo Project
    url: https://gitlab.com/endink/mediapipe4u-demo
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: GitHub
    url: https://github.com/endink/Mediapipe4u-plugin/
    hide_icon: false # set to true to hide the external link icon - defaults to false

aux_links:
  Just the Docs on GitHub:
    - https://opensource.labijie.com/Mediapipe4u-plugin/
  Just the Docs on GitHub:
    - https://opensource.labijie.com/Mediapipe4u-plugin/

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
