title: MediaPipe4U
description: UnrealEngine 插件，基于 Google MediaPipe 完成单目单目摄像头动作捕捉、表情捕捉

url: https://github.coms/endink/mediapipe4u-plugin
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-default-layout

nav_external_links:
  - title: Demo Project
    url: https://github.com/endink/MediaPipe4U-Demo
    hide_icon: false # set to true to hide the external link icon - defaults to false

